spring:
  data:
    mongodb:
      username: rudiger
      password: rudiger
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
